name: Metrics

on:
  # 定时触发，每天运行一次
  schedule:
    - cron: '0 0 * * *' # 每天午夜 (UTC 时间)
  workflow_dispatch:
  # 允许手动触发
  push:
    branches:
      - main
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ./metrics.svg
          base: "activity,community,repositories,metadata"
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_limit: 8
          plugin_commits: yes

      - name: Copy Metrics
        run: |
          cat ./metrics.svg >> README.md

      - name: Commit and push metrics
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Echin-h
          author_email: 197795131@qq.com
          message: "Update metrics"
          add: "README.md"